/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiImageProxyRouteImport } from './routes/api/image-proxy'
import { Route as AuthedDashboardRouteImport } from './routes/_authed.dashboard'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedCardsCardIdRouteImport } from './routes/_authed.cards.$cardId'
import { Route as AuthedBrowseGameIndexRouteImport } from './routes/_authed.browse.$game.index'
import { Route as AuthedCatalogGameCardIdRouteImport } from './routes/_authed.catalog.$game.$cardId'
import { Route as AuthedBrowseGameSetIdRouteImport } from './routes/_authed.browse.$game.$setId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageProxyRoute = ApiImageProxyRouteImport.update({
  id: '/api/image-proxy',
  path: '/api/image-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedCardsCardIdRoute = AuthedCardsCardIdRouteImport.update({
  id: '/cards/$cardId',
  path: '/cards/$cardId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBrowseGameIndexRoute = AuthedBrowseGameIndexRouteImport.update({
  id: '/browse/$game/',
  path: '/browse/$game/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCatalogGameCardIdRoute = AuthedCatalogGameCardIdRouteImport.update({
  id: '/catalog/$game/$cardId',
  path: '/catalog/$game/$cardId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBrowseGameSetIdRoute = AuthedBrowseGameSetIdRouteImport.update({
  id: '/browse/$game/$setId',
  path: '/browse/$game/$setId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/api/image-proxy': typeof ApiImageProxyRoute
  '/cards/$cardId': typeof AuthedCardsCardIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/browse/$game/$setId': typeof AuthedBrowseGameSetIdRoute
  '/catalog/$game/$cardId': typeof AuthedCatalogGameCardIdRoute
  '/browse/$game/': typeof AuthedBrowseGameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/api/image-proxy': typeof ApiImageProxyRoute
  '/cards/$cardId': typeof AuthedCardsCardIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/browse/$game/$setId': typeof AuthedBrowseGameSetIdRoute
  '/catalog/$game/$cardId': typeof AuthedCatalogGameCardIdRoute
  '/browse/$game': typeof AuthedBrowseGameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/api/image-proxy': typeof ApiImageProxyRoute
  '/_authed/cards/$cardId': typeof AuthedCardsCardIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/browse/$game/$setId': typeof AuthedBrowseGameSetIdRoute
  '/_authed/catalog/$game/$cardId': typeof AuthedCatalogGameCardIdRoute
  '/_authed/browse/$game/': typeof AuthedBrowseGameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/api/image-proxy'
    | '/cards/$cardId'
    | '/api/auth/$'
    | '/browse/$game/$setId'
    | '/catalog/$game/$cardId'
    | '/browse/$game/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/api/image-proxy'
    | '/cards/$cardId'
    | '/api/auth/$'
    | '/browse/$game/$setId'
    | '/catalog/$game/$cardId'
    | '/browse/$game'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/register'
    | '/_authed/dashboard'
    | '/api/image-proxy'
    | '/_authed/cards/$cardId'
    | '/api/auth/$'
    | '/_authed/browse/$game/$setId'
    | '/_authed/catalog/$game/$cardId'
    | '/_authed/browse/$game/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiImageProxyRoute: typeof ApiImageProxyRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image-proxy': {
      id: '/api/image-proxy'
      path: '/api/image-proxy'
      fullPath: '/api/image-proxy'
      preLoaderRoute: typeof ApiImageProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/cards/$cardId': {
      id: '/_authed/cards/$cardId'
      path: '/cards/$cardId'
      fullPath: '/cards/$cardId'
      preLoaderRoute: typeof AuthedCardsCardIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/browse/$game/': {
      id: '/_authed/browse/$game/'
      path: '/browse/$game'
      fullPath: '/browse/$game/'
      preLoaderRoute: typeof AuthedBrowseGameIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/catalog/$game/$cardId': {
      id: '/_authed/catalog/$game/$cardId'
      path: '/catalog/$game/$cardId'
      fullPath: '/catalog/$game/$cardId'
      preLoaderRoute: typeof AuthedCatalogGameCardIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/browse/$game/$setId': {
      id: '/_authed/browse/$game/$setId'
      path: '/browse/$game/$setId'
      fullPath: '/browse/$game/$setId'
      preLoaderRoute: typeof AuthedBrowseGameSetIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedCardsCardIdRoute: typeof AuthedCardsCardIdRoute
  AuthedBrowseGameSetIdRoute: typeof AuthedBrowseGameSetIdRoute
  AuthedCatalogGameCardIdRoute: typeof AuthedCatalogGameCardIdRoute
  AuthedBrowseGameIndexRoute: typeof AuthedBrowseGameIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedCardsCardIdRoute: AuthedCardsCardIdRoute,
  AuthedBrowseGameSetIdRoute: AuthedBrowseGameSetIdRoute,
  AuthedCatalogGameCardIdRoute: AuthedCatalogGameCardIdRoute,
  AuthedBrowseGameIndexRoute: AuthedBrowseGameIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiImageProxyRoute: ApiImageProxyRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
